# Linear Algebra

The Linear Algebra module of NumPy offers various methods to apply linear algebra on any numpy array.

You can find:

rank, determinant, trace, etc. of an array.
eigen values of matrices
matrix and vector products (dot, inner, outer,etc. product), matrix exponentiation
solve linear or tensor equations and much more!
Now, let us assume that we want to solve this linear equation set:

x + 2*y = 8
3*x + 4*y = 18
This problem can be solved using linalg.solve method as shown in example below:

In [1]:
import numpy as np

In [4]:
# coefficients
a = np.array([[1, 2], [3, 4]])
# constants
b = np.array([8, 18])

np.linalg.solve(a, b)

array([2., 3.])

In [3]:
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])

In [5]:
# rank of matrix
np.linalg.matrix_rank(A)

3

In [6]:
# trace of matrix
np.trace(A)

11

In [7]:
# determinant of matrix
np.linalg.det(A)

-306.0

In [8]:
# inverse of matrix
np.linalg.inv(A)

array([[ 0.17647059, -0.00326797, -0.02287582],
       [ 0.05882353, -0.13071895,  0.08496732],
       [-0.11764706,  0.1503268 ,  0.05228758]])

In [9]:
# matrix exponentiation
np.linalg.matrix_power(A, 3)

array([[336, 162, 228],
       [406, 162, 469],
       [698, 702, 905]])