# Saving and loading numpy arrays

The .npy format is the standard binary file format in NumPy for persisting a single arbitrary NumPy array on disk. The format stores all of the shape and dtype information necessary to reconstruct the array correctly even on another machine with a different architecture. The format is designed to be as simple as possible while achieving its limited goals.

The .npz format is the standard format for persisting multiple NumPy arrays on disk. A .npz file is a zip file containing multiple .npy files, one for each array.

np.save(filename, array) : saves a single array in npy format.

np.savez(filename, array_1[, array_2]) : saves multiple numpy arrays in npz format.

np.load(filename) : load a npy or npz format file.

In [1]:

import numpy as np

In [2]:
a = np.array([[1,2,3],
             [4,5,6]])

b = np.array([[6,5,4],
              [3,2,1]])

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:

b

array([[6, 5, 4],
       [3, 2, 1]])

In [5]:
np.save("a.npy", a)

In [6]:

a = np.load("a.npy")

In [7]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
np.savez("AB.npz", x=a, y=b)

In [9]:

arr = np.load("AB.npz")

In [10]:
arr['x']

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr['y']

array([[6, 5, 4],
       [3, 2, 1]])