# Array Creation

There are various ways to create arrays in NumPy.

For example, you can create an array from a regular Python list or tuple using the array function. The type of the resulting array is deduced from the type of the elements in the sequences.

In [1]:
mylist = [[1,2,3],
         [4,5,6]]

In [2]:
import numpy as np

In [3]:
arr = np.array(mylist)

In [4]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation. For example: np.zeros, np.ones, np.full, np.empty, np.random.random, np.random.randint etc.

In [5]:
arr = np.zeros((4,4), dtype='int')

In [6]:
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [7]:

arr.dtype

dtype('int64')

In [8]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
np.full((3,3), 6)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [10]:
np.random.random((2,2))

array([[0.93367762, 0.45096021],
       [0.46221988, 0.84806574]])

In [11]:

np.random.randint(1,10,(3,3))

array([[9, 9, 1],
       [3, 2, 2],
       [2, 7, 6]])

To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists.
arange: returns evenly spaced values within a given interval. step size is specified.
linspace: returns evenly spaced values within a given interval. num no. of elements are returned

In [12]:
np.array(list(range(10)))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [16]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [17]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])