# Array Operations

Plethora of built-in arithmetic functions are provided in NumPy.

Elementwise operation: We can use overloaded arithmetic operators to do element-wise operation on array to create a new array. In case of +=, -=, *= operators, the exsisting array is modified.

In [1]:
import numpy as np

In [2]:

arr = np.array([[1,2,3],
               [4,5,6]])

In [3]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [5]:
arr ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [6]:
arr += 1

In [7]:
arr

array([[2, 3, 4],
       [5, 6, 7]])

Unary operators: Many unary operations are provided as a method of ndarray class. This includes sum, min, max, etc. These functions can also be applied row-wise or column-wise by setting an axis parameter.

In [8]:
arr

array([[2, 3, 4],
       [5, 6, 7]])

In [9]:
arr.sum()


27

In [11]:
arr.sum(axis=0)

array([ 7,  9, 11])

In [12]:
arr.sum(axis=1)

array([ 9, 18])

In [13]:
arr.min(axis=0)

array([2, 3, 4])

Binary operators: These operations apply on array elementwise and a new array is created. You can use all basic arithmetic operators like +, -, /, , etc. In case of +=, -=, = operators, the exsisting array is modified.

In [14]:
a = np.array([[1,2],
             [3,4]])

b = np.array([[5,6],
             [7,8]])

In [15]:
a + b

array([[ 6,  8],
       [10, 12]])

Universal functions (ufunc): NumPy provides familiar mathematical functions such as sin, cos, exp, etc. These functions also operate elementwise on an array, producing an array as output.
Note: All the operations we did above using overloaded operators can be done using ufuncs like np.add, np.subtract, np.multiply, np.divide, np.sum, etc.

In [16]:
arr

array([[2, 3, 4],
       [5, 6, 7]])

In [17]:
np.sin(arr)

array([[ 0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ]])

In [18]:
np.exp(arr)

array([[   7.3890561 ,   20.08553692,   54.59815003],
       [ 148.4131591 ,  403.42879349, 1096.63315843]])