# Array Sorting

In [2]:
import numpy as np

In [3]:
arr = np.array([[1, 4, 2],
                [3, 4, 6],
                [0, -1, 5]])

In [4]:
np.sort(arr, axis=1)

array([[ 1,  2,  4],
       [ 3,  4,  6],
       [-1,  0,  5]])

In [5]:
np.sort(arr, axis=0)

array([[ 0, -1,  2],
       [ 1,  4,  5],
       [ 3,  4,  6]])

In [6]:
np.sort(arr, axis=None)

array([-1,  0,  1,  2,  3,  4,  4,  5,  6])