# Array Stacking and Splitting

Stacking


Several arrays can be stacked together along different axes.

np.vstack: To stack arrays along vertical axis.

np.hstack: To stack arrays along horizontal axis.

np.column_stack: To stack 1-D arrays as columns into 2-D arrays.

np.row_stack: To stack 1-D arrays as rows into 2-D arrays.

np.concatenate: To stack arrays along specified axis (axis is passed as argument).

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

In [3]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [4]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [5]:
c = np.array([0,0])

In [6]:
np.column_stack((a,c))

array([[1, 2, 0],
       [3, 4, 0]])

In [7]:

np.row_stack((a,c))

array([[1, 2],
       [3, 4],
       [0, 0]])

In [8]:
np.concatenate((a,b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# Splitting

For splitting, we have these fuctions:

np.hsplit: Split array along horizontal axis.

np.vsplit: Split array along vertical axis.

np.array_split: Split array along specified axis.

In [9]:
a = np.array([[1, 3, 5, 7, 9, 11],
              [2, 4, 6, 8, 10, 12]])

In [10]:
np.hsplit(a, 2)

[array([[1, 3, 5],
        [2, 4, 6]]), array([[ 7,  9, 11],
        [ 8, 10, 12]])]

In [11]:
np.vsplit(a, 2)

[array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]

In [12]:
np.array_split(a, 2, axis=1)

[array([[1, 3, 5],
        [2, 4, 6]]), array([[ 7,  9, 11],
        [ 8, 10, 12]])]